@echo off
REM =====================================================================
REM  Cài đặt Task Scheduler — Skill Sync Daemon
REM  SAP ABAP Agent
REM =====================================================================
REM  Chạy file này với quyền Administrator để tạo task tự động.
REM =====================================================================

echo ====================================================
echo  SAP ABAP Agent — Skill Sync Daemon Setup
echo ====================================================
echo.
echo  File nay se tao Task Scheduler de tu dong
echo  dong bo skills/agents moi nhat tu GitHub
echo  moi 30 phut.
echo.
echo  Yeu cau: Chay voi quyen Administrator!
echo.

REM ---- CONFIG ----
set "PYTHON_PATH=C:\Python314\python.exe"
set "SCRIPT_PATH=D:\__StormShyn\sap-abap-agent\reference\scripts\sync_skills.py"
set "WRAPPER_PATH=D:\__StormShyn\sap-abap-agent\reference\scripts\run_sync_skills.bat"
set "WORKING_DIR=D:\__StormShyn\sap-abap-agent"
set "TASK_NAME=SAP ABAP Agent - Skill Sync"
set "LOG_FILE=D:\__StormShyn\sap-abap-agent\.sap-abap-agent\task_scheduler.log"
REM -----------------

REM Kiem tra file ton tai
if not exist "%PYTHON_PATH%" (
    echo [LOI] Khong tim thay Python tai: %PYTHON_PATH%
    echo.
    echo Hay sua PYTHON_PATH trong file nay.
    pause
    exit /b 1
)

if not exist "%SCRIPT_PATH%" (
    echo [LOI] Khong tim thay script tai: %SCRIPT_PATH%
    pause
    exit /b 1
)

echo [1/4] Dang xoa task cu (neu co)...
schtasks /delete /tn "%TASK_NAME%" /f >nul 2>&1

echo [2/4] Tao wrapper script de tranh van de quoting...
REM Tao wrapper .bat (khong co ky tu dac biet, an toan cho Task Scheduler)
(
echo @echo off
echo REM === SAP ABAP Agent Skill Sync ===
echo REM Generated by install-task-scheduler.bat
echo.
echo "%PYTHON_PATH%" "%SCRIPT_PATH%" ^>^> "%LOG_FILE%" 2^>^&1
) > "%WRAPPER_PATH%"

echo [3/4] Dang tao task moi...
schtasks /create ^
    /tn "%TASK_NAME%" ^
    /tr "%WRAPPER_PATH%" ^
    /sc minute ^
    /mo 30 ^
    /st 08:00 ^
    /ed 31/12/2030 ^
    /du 9999:00 ^
    /rl HIGHEST ^
    /f

if %ERRORLEVEL% NEQ 0 (
    echo [LOI] Khong the tao task. Hay chay lai voi quyen Administrator.
    pause
    exit /b 1
)

echo [4/4] Kiem tra task da tao...
schtasks /query /tn "%TASK_NAME%" /fo list 2>&1 | findstr /i "TaskName" >nul
if %ERRORLEVEL% EQU 0 (
    echo [OK] Task da duoc tao thanh cong!
) else (
    echo [LOI] Task chua duoc tao.
    pause
    exit /b 1
)

echo [5/5] Chay thu lan dau...
start /B /MIN "" "%WRAPPER_PATH%"

echo.
echo ====================================================
echo  HOAN TAT!
echo ====================================================
echo.
echo  Task Name:  %TASK_NAME%
echo  Schedule:   Moi 30 phut
echo  Python:     %PYTHON_PATH%
echo  Script:     %SCRIPT_PATH%
echo.
echo  De kiem tra trong Task Scheduler:
echo    1. Mo Task Scheduler (taskschd.msc)
echo    2. Tim task "%TASK_NAME%"
echo    3. Right-click > Run de chay thu
echo.
echo  De xoa task:
echo    schtasks /delete /tn "%TASK_NAME%" /f
echo.
echo  Log file: %LOG_FILE%
echo.

pause
