@echo off
REM =====================================================================
REM  Cai dat Task Scheduler - Cron that cho sap-daily-learner
REM  SAP ABAP Agent
REM =====================================================================
REM  Chay file nay voi quyen Administrator de tao task tu dong.
REM
REM  QUAN TRONG - day CHI la buoc DAT LICH, KHONG tu BAT cron:
REM  Sau khi cai xong, task se tu chay moi 5 phut nhung se KHONG LAM GI CA
REM  (no-op) cho toi khi ban bat opt-in gate rieng - xem huong dan cuoi
REM  script nay (in ra sau khi cai xong), hoac skills/sap-daily-learner/SKILL.md.
REM  Ly do tach 2 buoc: moi lan cron thuc su chay se goi Claude Code that,
REM  ton chi phi API - khong nen tu bat ngam khi moi cai dat.
REM =====================================================================

echo ====================================================
echo  SAP ABAP Agent - Daily Learner Cron Setup
echo ====================================================
echo.
echo  File nay se tao Task Scheduler de kiem tra (tick)
echo  hang doi job cron cua sap-daily-learner moi 5 phut.
echo  Tick chi thuc su goi Claude Code khi co job DEN HAN.
echo.
echo  Yeu cau: Chay voi quyen Administrator!
echo  QUAN TRONG: cron van TAT sau khi cai - xem huong dan in ra cuoi cung.
echo.

REM ---- CONFIG (sua neu Python/duong dan clone plugin khac) ----
set "PYTHON_PATH=C:\Python314\python.exe"
set "PLUGIN_DIR=D:\__StormShyn\sap-abap-agent"
set "SCRIPT_PATH=%PLUGIN_DIR%\reference\scripts\cron_manage.py"
set "WRAPPER_PATH=%PLUGIN_DIR%\reference\scripts\run_cron_tick.bat"
set "TASK_NAME=SAP ABAP Agent - Daily Learner Cron Tick"
set "LOG_FILE=%PLUGIN_DIR%\.sap-abap-agent\cron_tick.log"
REM --------------------------------------------------------------

if not exist "%PYTHON_PATH%" (
    echo [LOI] Khong tim thay Python tai: %PYTHON_PATH%
    echo.
    echo Hay sua PYTHON_PATH trong file nay.
    pause
    exit /b 1
)

if not exist "%SCRIPT_PATH%" (
    echo [LOI] Khong tim thay script tai: %SCRIPT_PATH%
    pause
    exit /b 1
)

echo [1/4] Dang xoa task cu (neu co)...
schtasks /delete /tn "%TASK_NAME%" /f >nul 2>&1

echo [2/4] Tao wrapper script de tranh van de quoting...
REM Gia dinh agent-home mac dinh (%%USERPROFILE%%\.sap-abap-agent) - neu ban
REM dung SAP_ABAP_AGENT_HOME override (VD dev/test ngay trong repo), sua tay
REM dong "cron_manage.py tick" ben duoi cho dung thu muc do.
(
echo @echo off
echo REM === SAP ABAP Agent Daily Learner Cron Tick ===
echo REM Generated by install-daily-learner-cron.bat
echo.
echo "%PYTHON_PATH%" "%SCRIPT_PATH%" tick "%%USERPROFILE%%\.sap-abap-agent" ^>^> "%LOG_FILE%" 2^>^&1
) > "%WRAPPER_PATH%"

echo [3/4] Dang tao task moi (tick moi 5 phut)...
schtasks /create ^
    /tn "%TASK_NAME%" ^
    /tr "%WRAPPER_PATH%" ^
    /sc minute ^
    /mo 5 ^
    /st 08:00 ^
    /ed 31/12/2030 ^
    /du 9999:00 ^
    /rl HIGHEST ^
    /f

if %ERRORLEVEL% NEQ 0 (
    echo [LOI] Khong the tao task. Hay chay lai voi quyen Administrator.
    pause
    exit /b 1
)

echo [4/4] Kiem tra task da tao...
schtasks /query /tn "%TASK_NAME%" /fo list 2>&1 | findstr /i "TaskName" >nul
if %ERRORLEVEL% EQU 0 (
    echo [OK] Task da duoc tao thanh cong!
) else (
    echo [LOI] Task chua duoc tao.
    pause
    exit /b 1
)

echo.
echo ====================================================
echo  HOAN TAT - NHUNG CRON VAN DANG TAT (opt-in mac dinh)
echo ====================================================
echo.
echo  Task Name:  %TASK_NAME%
echo  Schedule:   Tick moi 5 phut (no-op cho toi khi co job DEN HAN va cron DA BAT)
echo  Log file:   %LOG_FILE%
echo.
echo  Task tren se tu chay dung gio nhung KHONG lam gi (no-op) cho toi khi ban
echo  BAT cron that su bang 1 trong 2 cach:
echo.
echo    Cach 1 (nhanh, khong can restart) - tao file marker:
echo      mkdir "%%USERPROFILE%%\.sap-abap-agent\cron" 2^>nul
echo      type nul ^> "%%USERPROFILE%%\.sap-abap-agent\cron\ENABLED"
echo.
echo    Cach 2 - bien moi truong he thong (System Properties ^> Environment
echo    Variables ^> System variables ^> New): SAP_ABAP_AGENT_CRON_ENABLED=1
echo.
echo  Sau khi bat, them it nhat 1 job de cron co viec de lam, vi du tip hang ngay:
echo    "%PYTHON_PATH%" "%SCRIPT_PATH%" add "%%USERPROFILE%%\.sap-abap-agent" ^^
echo        daily-tip "/sap-daily-learner cho toi 1 tip hoc SAP hom nay dua tren tien do hien tai" daily@08:00
echo.
echo  Xem trang thai / chi phi da dung:
echo    "%PYTHON_PATH%" "%SCRIPT_PATH%" status "%%USERPROFILE%%\.sap-abap-agent"
echo.
echo  De xoa task nay:
echo    schtasks /delete /tn "%TASK_NAME%" /f
echo.

pause
